export default [
  {
    name: "door",
    type: "glbModel",
    path: "/models/door.glb",
    urlPathname: "/",
  },
  {
    no: 1,
    name: "catPlayground",
    type: "glbModel",
    path: "/models/catPlayground-test.glb",
    urlPathname: "/",
  },
  {
    no: 2,
    name: "eatingCat",
    type: "glbModel",
    path: "/models/eatingCat.glb",
    urlPathname: "/scene/cat-eating",
  },
  {
    no: 3,
    name: "playingCat",
    type: "glbModel",
    path: "/models/playingCat.glb",
    urlPathname: "/scene/cat-playing",
  },
  {
    no: 4,
    name: "standingCat",
    type: "glbModel",
    path: "/models/standingCat.glb",
    urlPathname: "/scene/cat-standing",
  },
  {
    no: 5,
    name: "lyingCat",
    type: "glbModel",
    path: "/models/lyingCat.glb",
    urlPathname: "/scene/cat-lying",
  },
  {
    no: 6,
    name: "sideLyingCat",
    type: "glbModel",
    path: "/models/sideLyingCat.glb",
    urlPathname: "/scene/cat-side-lying",
  },
];
